"""add_phase2_tailoring_tables

Revision ID: e3f5bea2636a
Revises:
Create Date: 2026-03-31 15:20:09.569769

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e3f5bea2636a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_bullets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('skills_referenced', sa.Text(), nullable=True, comment='JSON array of skill names — denormalized for LLM context injection'),
    sa.Column('metrics', sa.Text(), nullable=True, comment='JSON array of quantitative metrics extracted from bullet'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("section IN ('SUMMARY', 'EXPERIENCE', 'SKILLS', 'PROJECTS', 'CERTIFICATIONS')", name='ck_parsed_bullets_section'),
    sa.ForeignKeyConstraint(['profile_id'], ['resume_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'original_text', name='uq_parsed_bullet_identity')
    )
    with op.batch_alter_table('parsed_bullets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_bullets_profile_id'), ['profile_id'], unique=False)

    op.create_table('tailoring_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('target_tier', sa.Integer(), nullable=False),
    sa.Column('emphasis_areas', sa.Text(), nullable=True, comment='JSON array of emphasis keywords for LLM prompt context'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('target_tier BETWEEN 1 AND 3', name='ck_tailoring_tier'),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['resume_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'profile_id', name='uq_tailoring_request_identity')
    )
    with op.batch_alter_table('tailoring_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tailoring_requests_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tailoring_requests_profile_id'), ['profile_id'], unique=False)

    op.create_table('skill_gaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('job_requires', sa.Boolean(), nullable=False),
    sa.Column('resume_has', sa.Boolean(), nullable=False),
    sa.Column('proficiency', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('language', 'framework', 'infrastructure', 'database', 'cloud', 'methodology', 'soft_skill', 'domain', 'tool')", name='ck_skill_gap_category'),
    sa.CheckConstraint("proficiency IS NULL OR proficiency IN ('expert', 'proficient', 'familiar', 'learning')", name='ck_skill_gap_proficiency'),
    sa.ForeignKeyConstraint(['request_id'], ['tailoring_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'skill_name', name='uq_skill_gap_identity')
    )
    with op.batch_alter_table('skill_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_gaps_request_id'), ['request_id'], unique=False)

    op.create_table('tailored_bullets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('rewritten_text', sa.Text(), nullable=False),
    sa.Column('xyz_format', sa.Boolean(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('relevance_score BETWEEN 0.0 AND 1.0', name='ck_tailored_bullet_score'),
    sa.ForeignKeyConstraint(['request_id'], ['tailoring_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tailored_bullets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tailored_bullets_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tailored_bullets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tailored_bullets_request_id'))

    op.drop_table('tailored_bullets')
    with op.batch_alter_table('skill_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_gaps_request_id'))

    op.drop_table('skill_gaps')
    with op.batch_alter_table('tailoring_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tailoring_requests_profile_id'))
        batch_op.drop_index(batch_op.f('ix_tailoring_requests_job_id'))

    op.drop_table('tailoring_requests')
    with op.batch_alter_table('parsed_bullets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_bullets_profile_id'))

    op.drop_table('parsed_bullets')
    # ### end Alembic commands ###
